version: "3.8"
services:
  cloudreve:
    container_name: cloudreve
    build: ./
    restart: unless-stopped
    ports:
      - "5212:5212"
    volumes:
      - temp_data:/data
      - ./data/cloudreve/uploads:/cloudreve/uploads
      - ./data/cloudreve/conf.ini:/cloudreve/conf.ini
      - ./data/cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - ./data/cloudreve/avatar:/cloudreve/avatar
    networks:
      internal:
        ipv4_address: 172.16.238.10
    depends_on:
      - aria2
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro # third party image, please keep notice what you are doing
    restart: unless-stopped
    environment:
      - RPC_PORT=6800
      - RPC_SECRET=your_aria_rpc_token
    volumes:
      - temp_data:/data
      - ./data/cloudreve/aria2/config:/config
    networks:
      internal:
        ipv4_address: 172.16.238.11
volumes:
  temp_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data/cloudreve
      o: bind
networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
